#############################################################################
# Makefile for building: PRadEventViewer
# Generated by qmake (2.01a) (Qt 4.8.5) on: Mon Mar 21 18:58:47 2016
# Project:  QMakefile.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile QMakefile.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -std=c++0x -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib64/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -Iinclude -Ithirdparty/include -I/u/site/coda/3.02/common/include -I/u/site/coda/3.02/common/include -I/u/apps/root/6.02.00/root-6.02.00/include -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-z,relro
LIBS          = $(SUBLIBS)  -L/usr/lib64 -Lthirdparty/lib -lcaenhvwrapper -L/site/coda/3.02/Linux-x86_64/lib -levio -levioxx -let -L/u/apps/root/6.02.00/root/lib -lCore -lRint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lGui -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/PRadEventViewer.cpp \
		src/HyCalModule.cpp \
		src/HyCalScene.cpp \
		src/HyCalView.cpp \
		src/Spectrum.cpp \
		src/SpectrumSettingPanel.cpp \
		src/HtmlDelegate.cpp \
		src/PRadEvioParser.cpp \
		src/PRadDataHandler.cpp \
		src/PRadETChannel.cpp \
		src/ETSettingPanel.cpp \
		src/PRadLogBox.cpp \
		src/PRadHVChannel.cpp \
		src/PRadException.cpp \
		src/PRadHistCanvas.cpp \
		src/QRootCanvas.cpp moc_PRadEventViewer.cpp \
		moc_HyCalScene.cpp \
		moc_HyCalView.cpp \
		moc_Spectrum.cpp \
		moc_SpectrumSettingPanel.cpp \
		moc_ETSettingPanel.cpp \
		moc_PRadLogBox.cpp \
		moc_PRadHistCanvas.cpp \
		moc_QRootCanvas.cpp
OBJECTS       = main.o \
		PRadEventViewer.o \
		HyCalModule.o \
		HyCalScene.o \
		HyCalView.o \
		Spectrum.o \
		SpectrumSettingPanel.o \
		HtmlDelegate.o \
		PRadEvioParser.o \
		PRadDataHandler.o \
		PRadETChannel.o \
		ETSettingPanel.o \
		PRadLogBox.o \
		PRadHVChannel.o \
		PRadException.o \
		PRadHistCanvas.o \
		QRootCanvas.o \
		moc_PRadEventViewer.o \
		moc_HyCalScene.o \
		moc_HyCalView.o \
		moc_Spectrum.o \
		moc_SpectrumSettingPanel.o \
		moc_ETSettingPanel.o \
		moc_PRadLogBox.o \
		moc_PRadHistCanvas.o \
		moc_QRootCanvas.o
DIST          = /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/shared.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		QMakefile.pro
QMAKE_TARGET  = PRadEventViewer
DESTDIR       = 
TARGET        = PRadEventViewer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QMakefile.pro  /usr/lib64/qt4/mkspecs/linux-g++/qmake.conf /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/shared.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtCore.prl
	$(QMAKE) -o Makefile QMakefile.pro
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt4/mkspecs/common/g++-base.conf:
/usr/lib64/qt4/mkspecs/common/g++-unix.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/modules/qt_phonon.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
/usr/lib64/qt4/mkspecs/features/release.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/shared.prf:
/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/qt.prf:
/usr/lib64/qt4/mkspecs/features/unix/thread.prf:
/usr/lib64/qt4/mkspecs/features/moc.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile QMakefile.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/PRadEventViewer1.0.0 || $(MKDIR) .tmp/PRadEventViewer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/PRadEventViewer1.0.0/ && $(COPY_FILE) --parents include/PRadEventViewer.h include/HyCalModule.h include/HyCalScene.h include/HyCalView.h include/Spectrum.h include/SpectrumSettingPanel.h include/HtmlDelegate.h include/PRadEvioParser.h include/PRadDataHandler.h include/PRadETChannel.h include/ETSettingPanel.h include/PRadLogBox.h include/PRadHVChannel.h include/PRadException.h include/PRadHistCanvas.h include/QRootCanvas.h .tmp/PRadEventViewer1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/PRadEventViewer.cpp src/HyCalModule.cpp src/HyCalScene.cpp src/HyCalView.cpp src/Spectrum.cpp src/SpectrumSettingPanel.cpp src/HtmlDelegate.cpp src/PRadEvioParser.cpp src/PRadDataHandler.cpp src/PRadETChannel.cpp src/ETSettingPanel.cpp src/PRadLogBox.cpp src/PRadHVChannel.cpp src/PRadException.cpp src/PRadHistCanvas.cpp src/QRootCanvas.cpp .tmp/PRadEventViewer1.0.0/ && (cd `dirname .tmp/PRadEventViewer1.0.0` && $(TAR) PRadEventViewer1.0.0.tar PRadEventViewer1.0.0 && $(COMPRESS) PRadEventViewer1.0.0.tar) && $(MOVE) `dirname .tmp/PRadEventViewer1.0.0`/PRadEventViewer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/PRadEventViewer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_PRadEventViewer.cpp moc_HyCalScene.cpp moc_HyCalView.cpp moc_Spectrum.cpp moc_SpectrumSettingPanel.cpp moc_ETSettingPanel.cpp moc_PRadLogBox.cpp moc_PRadHistCanvas.cpp moc_QRootCanvas.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_PRadEventViewer.cpp moc_HyCalScene.cpp moc_HyCalView.cpp moc_Spectrum.cpp moc_SpectrumSettingPanel.cpp moc_ETSettingPanel.cpp moc_PRadLogBox.cpp moc_PRadHistCanvas.cpp moc_QRootCanvas.cpp
moc_PRadEventViewer.cpp: include/PRadEventViewer.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) include/PRadEventViewer.h -o moc_PRadEventViewer.cpp

moc_HyCalScene.cpp: include/HyCalScene.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) include/HyCalScene.h -o moc_HyCalScene.cpp

moc_HyCalView.cpp: include/HyCalView.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) include/HyCalView.h -o moc_HyCalView.cpp

moc_Spectrum.cpp: include/Spectrum.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) include/Spectrum.h -o moc_Spectrum.cpp

moc_SpectrumSettingPanel.cpp: include/SpectrumSettingPanel.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) include/SpectrumSettingPanel.h -o moc_SpectrumSettingPanel.cpp

moc_ETSettingPanel.cpp: include/ETSettingPanel.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) include/ETSettingPanel.h -o moc_ETSettingPanel.cpp

moc_PRadLogBox.cpp: include/PRadLogBox.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) include/PRadLogBox.h -o moc_PRadLogBox.cpp

moc_PRadHistCanvas.cpp: include/PRadHistCanvas.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) include/PRadHistCanvas.h -o moc_PRadHistCanvas.cpp

moc_QRootCanvas.cpp: include/QRootCanvas.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) include/QRootCanvas.h -o moc_QRootCanvas.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

PRadEventViewer.o: src/PRadEventViewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PRadEventViewer.o src/PRadEventViewer.cpp

HyCalModule.o: src/HyCalModule.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HyCalModule.o src/HyCalModule.cpp

HyCalScene.o: src/HyCalScene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HyCalScene.o src/HyCalScene.cpp

HyCalView.o: src/HyCalView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HyCalView.o src/HyCalView.cpp

Spectrum.o: src/Spectrum.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Spectrum.o src/Spectrum.cpp

SpectrumSettingPanel.o: src/SpectrumSettingPanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SpectrumSettingPanel.o src/SpectrumSettingPanel.cpp

HtmlDelegate.o: src/HtmlDelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HtmlDelegate.o src/HtmlDelegate.cpp

PRadEvioParser.o: src/PRadEvioParser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PRadEvioParser.o src/PRadEvioParser.cpp

PRadDataHandler.o: src/PRadDataHandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PRadDataHandler.o src/PRadDataHandler.cpp

PRadETChannel.o: src/PRadETChannel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PRadETChannel.o src/PRadETChannel.cpp

ETSettingPanel.o: src/ETSettingPanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ETSettingPanel.o src/ETSettingPanel.cpp

PRadLogBox.o: src/PRadLogBox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PRadLogBox.o src/PRadLogBox.cpp

PRadHVChannel.o: src/PRadHVChannel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PRadHVChannel.o src/PRadHVChannel.cpp

PRadException.o: src/PRadException.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PRadException.o src/PRadException.cpp

PRadHistCanvas.o: src/PRadHistCanvas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PRadHistCanvas.o src/PRadHistCanvas.cpp

QRootCanvas.o: src/QRootCanvas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QRootCanvas.o src/QRootCanvas.cpp

moc_PRadEventViewer.o: moc_PRadEventViewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PRadEventViewer.o moc_PRadEventViewer.cpp

moc_HyCalScene.o: moc_HyCalScene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_HyCalScene.o moc_HyCalScene.cpp

moc_HyCalView.o: moc_HyCalView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_HyCalView.o moc_HyCalView.cpp

moc_Spectrum.o: moc_Spectrum.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Spectrum.o moc_Spectrum.cpp

moc_SpectrumSettingPanel.o: moc_SpectrumSettingPanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SpectrumSettingPanel.o moc_SpectrumSettingPanel.cpp

moc_ETSettingPanel.o: moc_ETSettingPanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ETSettingPanel.o moc_ETSettingPanel.cpp

moc_PRadLogBox.o: moc_PRadLogBox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PRadLogBox.o moc_PRadLogBox.cpp

moc_PRadHistCanvas.o: moc_PRadHistCanvas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PRadHistCanvas.o moc_PRadHistCanvas.cpp

moc_QRootCanvas.o: moc_QRootCanvas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QRootCanvas.o moc_QRootCanvas.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

